package com.smartitsm.sla.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.smartitsm.common.entity.BaseEntity;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;

/**
 * SLA breach risk prediction entity.
 *
 * Stores per-ticket risk predictions generated by
 * {@code SlaBreachPredictionService}. Risk score is a 0..1 probability
 * computed from the four-factor weighted algorithm.
 */
@Builder
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("t_sla_breach_risk")
public class SlaBreachRisk extends BaseEntity {

    private Long ticketId;

    private Long slaPolicyId;

    // Progress tracking
    private Double currentProgress;   // 0..100
    private Double expectedProgress;  // 0..100

    // Prediction
    private Double riskScore;         // 0..1
    private LocalDateTime predictedBreachAt;

    // Status
    private String status;            // PREDICTED, BREACHED, SAFE, EXPIRED

    // Ticket snapshot for context
    private String ticketCategory;
    private String ticketPriority;
    private LocalDateTime slaDueAt;
}