spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartitsm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
      config:
        enabled: true
        server-addr: localhost:8848

server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.smartitsm.ticket: DEBUG
